### ISSUE TITLE
Check references to master

### ISSUE THREAD

**Issue by marsavar** [guardian/fastly-api-client#32]
The master branch of this repository has been migrated to main using the [master-to-main](https://github.com/guardian/master-to-main) tool.

  Some files in the repository contain the word master. Please check the following files and update where required:

  - [x] [CONTRIBUTING.md](https://github.com/guardian/fastly-api-client/blob/main/CONTRIBUTING.md)
- [x] [.github/workflows/snyk.yml](https://github.com/guardian/fastly-api-client/blob/main/.github/workflows/snyk.yml)

**Comment by ioannakok** [comment]
Done here: https://github.com/guardian/fastly-api-client/pull/35/commits/bdd13c850126e86feaa6f2b4ef64a5a93abb7057
